# -*- coding: utf-8 -*-
"""IsoForestGenerativeClassifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kpy2itPtPdjp-GyvQ6yKqlMHXL2XzWmX
"""

import importlib

import numpy as np
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.validation import check_X_y, check_array, check_is_fitted
from sklearn.preprocessing import QuantileTransformer, LabelEncoder
from sklearn.linear_model import LogisticRegression
from coniferest.aadforest import AADForest
from coniferest.label import Label
from coniferest.pineforest import PineForest


def _get_isotree_isolationforest():
    return importlib.import_module("isotree").IsolationForest

class IsoForestGenerativeClassifier(ClassifierMixin, BaseEstimator):
    _estimator_type = "classifier"
    _eps = 1e-12

    def __init__(
        self,
        n_estimators=100,
        max_samples=256,
        ndim=1,  # Fixed: exposed parameter, defaulted to 1 (standard iForest)
        bootstrap=False,
        n_jobs=None,
        random_state=None,
        verbose=0,
        max_depth=None,
        calibration="discriminator", # Options: 'zscore', 'quantile', 'discriminator'
        global_scale=1.0,
    ):
        self.n_estimators = n_estimators
        self.max_samples = max_samples
        self.ndim = ndim
        self.bootstrap = bootstrap
        self.n_jobs = n_jobs
        self.random_state = random_state
        self.verbose = verbose
        self.max_depth = max_depth

        # 'quantile' forces scores to N(0,1) distribution (Robust)
        # 'zscore' uses mean/std (Standard)
        # 'discriminator' trains a LogisticRegression on top of scores (Best accuracy)
        self.calibration = calibration
        self.global_scale = global_scale

    def _make_iforest(self, random_state):
        return _get_isotree_isolationforest()(
            n_estimators=self.n_estimators,
            max_samples=self.max_samples,
            max_depth=self.max_depth,
            n_jobs=self.n_jobs,
            random_state=random_state,
            bootstrap=self.bootstrap,
            ndim=self.ndim,
            missing_action="fail",
            scoring_metric="depth",
            penalize_range=True, # Improved scoring smoothness
        )

    def fit(self, X, y):
        X, y = check_X_y(X, y, accept_sparse=False, dtype=np.float64)

        # Handle class labels cleanly
        self.le_ = LabelEncoder()
        y_enc = self.le_.fit_transform(y)
        self.classes_ = self.le_.classes_
        n_classes = len(self.classes_)

        if n_classes < 2:
            raise ValueError("Need at least 2 classes.")

        self.n_classes_ = n_classes
        self.class_priors_ = np.bincount(y_enc) / float(len(y))
        self.log_class_priors_ = np.log(self.class_priors_ + self._eps)

        self.iforests_ = []
        self.calibrators_ = [] # Stores Mean/Std OR QuantileTransformers

        rng = np.random.RandomState(self.random_state)

        # 1. Fit an iForest for each class
        for k in range(n_classes):
            Xk = X[y_enc == k]

            # Create and fit forest
            rs_k = None if self.random_state is None else rng.randint(0, 2**31 - 1)
            iforest_k = self._make_iforest(random_state=rs_k)
            iforest_k.fit(Xk)
            self.iforests_.append(iforest_k)

            # Get Training Scores for calibration
            # We negate because isotree returns higher=anomalous, we want higher=normal
            scores_k = -iforest_k.decision_function(Xk)

            # 2. Fit Calibrator
            if self.calibration == "quantile":
                # Maps arbitrary score dist to Standard Normal N(0,1)
                qt = QuantileTransformer(output_distribution='normal', n_quantiles=min(len(Xk), 1000))
                qt.fit(scores_k.reshape(-1, 1))
                self.calibrators_.append(qt)

            elif self.calibration == "zscore" or self.calibration == "discriminator":
                # For discriminator, we still z-score normalize inputs for stability
                mu_k = scores_k.mean()
                std_k = scores_k.std()
                if std_k <= 0: std_k = 1.0
                self.calibrators_.append((mu_k, std_k))

        # 3. If Discriminator, train the meta-classifier
        if self.calibration == "discriminator":
            # Generate feature matrix S (samples x classes)
            S_train = self._get_raw_scores(X, apply_zscore=True)
            self.discriminator_ = LogisticRegression(class_weight='balanced')
            self.discriminator_.fit(S_train, y_enc)

        self.n_features_in_ = X.shape[1]
        return self

    def _get_raw_scores(self, X, apply_zscore=False):
        """Helper to get scores matrix (N_samples, N_classes)"""
        n_samples = X.shape[0]
        S = np.zeros((n_samples, self.n_classes_), dtype=float)

        for k, iforest_k in enumerate(self.iforests_):
            # Raw normality score
            s_k = -iforest_k.decision_function(X)

            # Apply calibration transform
            if self.calibration == "quantile":
                # Transform expects 2D array
                s_k = self.calibrators_[k].transform(s_k.reshape(-1, 1)).flatten()
            elif apply_zscore or self.calibration == "zscore":
                mu_k, std_k = self.calibrators_[k]
                s_k = (s_k - mu_k) / std_k

            S[:, k] = s_k
        return S

    def predict_proba(self, X):
        check_is_fitted(self, ["iforests_", "classes_"])
        X = check_array(X, accept_sparse=False, dtype=np.float64)

        # PATH A: Discriminative (Logistic Regression on top of scores)
        if self.calibration == "discriminator":
            S = self._get_raw_scores(X, apply_zscore=True)
            return self.discriminator_.predict_proba(S)

        # PATH B: Generative (Argmax of scaled priors)
        S = self._get_raw_scores(X)

        # Log-Posterior ~ Scale * Score + LogPrior
        # Note: If calibration='quantile', S is effectively log-likelihood ratio
        # relative to the class median, scaled to Normal dist.
        L = self.global_scale * S + self.log_class_priors_

        # Softmax stability trick
        max_L = np.max(L, axis=1, keepdims=True)
        exp_L = np.exp(L - max_L)
        Z = exp_L.sum(axis=1, keepdims=True)
        return exp_L / Z

    def predict(self, X):
        P = self.predict_proba(X)
        idx = np.argmax(P, axis=1)
        return self.classes_[idx]


class PineForestGenerativeClassifier(ClassifierMixin, BaseEstimator):
    """Multiclass classifier built from one PineForest per class.

    The classifier fits one class-conditional PineForest model for each class,
    converts the resulting classwise normality scores into a score matrix, and
    turns those scores into multiclass probabilities via quantile, z-score, or
    discriminator calibration.
    """

    _estimator_type = "classifier"
    _eps = 1e-12

    def __init__(
        self,
        n_estimators=100,
        max_samples=256,
        bootstrap=False,
        n_jobs=None,
        random_state=None,
        verbose=0,
        max_depth=None,
        calibration="discriminator",
        global_scale=1.0,
    ):
        self.n_estimators = n_estimators
        self.max_samples = max_samples
        self.bootstrap = bootstrap
        self.n_jobs = n_jobs
        self.random_state = random_state
        self.verbose = verbose
        self.max_depth = max_depth
        self.calibration = calibration
        self.global_scale = global_scale

    def _make_pineforest(self, random_state):
        pineforest = PineForest(
            n_trees=self.n_estimators,
            n_subsamples=self.max_samples,
            max_depth=self.max_depth,
            n_jobs=-1 if self.n_jobs is None else self.n_jobs,
            random_seed=random_state,
        )
        if self.bootstrap:
            pineforest.bootstrap_samples = True
        return pineforest

    def _score_pine_normality(self, model, X):
        return model.score_samples(X)

    def fit(self, X, y):
        X, y = check_X_y(X, y, accept_sparse=False, dtype=np.float64)

        self.le_ = LabelEncoder()
        y_enc = self.le_.fit_transform(y)
        self.classes_ = self.le_.classes_
        n_classes = len(self.classes_)

        if n_classes < 2:
            raise ValueError("Need at least 2 classes.")

        self.n_classes_ = n_classes
        self.class_priors_ = np.bincount(y_enc) / float(len(y))
        self.log_class_priors_ = np.log(self.class_priors_ + self._eps)

        self.pineforests_ = []
        self.calibrators_ = []

        rng = np.random.RandomState(self.random_state)

        for k in range(n_classes):
            Xk = X[y_enc == k]

            rs_k = None if self.random_state is None else rng.randint(0, 2**31 - 1)
            pineforest_k = self._make_pineforest(random_state=rs_k)
            pineforest_k.fit(Xk)
            self.pineforests_.append(pineforest_k)

            scores_k = self._score_pine_normality(pineforest_k, Xk)

            if self.calibration == "quantile":
                qt = QuantileTransformer(output_distribution="normal", n_quantiles=min(len(Xk), 1000))
                qt.fit(scores_k.reshape(-1, 1))
                self.calibrators_.append(qt)
            elif self.calibration == "zscore" or self.calibration == "discriminator":
                mu_k = scores_k.mean()
                std_k = scores_k.std()
                if std_k <= 0:
                    std_k = 1.0
                self.calibrators_.append((mu_k, std_k))
            else:
                raise ValueError("calibration must be one of {'quantile', 'zscore', 'discriminator'}")

        if self.calibration == "discriminator":
            S_train = self._get_raw_scores(X, apply_zscore=True)
            self.discriminator_ = LogisticRegression(class_weight="balanced")
            self.discriminator_.fit(S_train, y_enc)

        self.n_features_in_ = X.shape[1]
        return self

    def _get_raw_scores(self, X, apply_zscore=False):
        n_samples = X.shape[0]
        S = np.zeros((n_samples, self.n_classes_), dtype=float)

        for k, pineforest_k in enumerate(self.pineforests_):
            s_k = self._score_pine_normality(pineforest_k, X)

            if self.calibration == "quantile":
                s_k = self.calibrators_[k].transform(s_k.reshape(-1, 1)).flatten()
            elif apply_zscore or self.calibration == "zscore":
                mu_k, std_k = self.calibrators_[k]
                s_k = (s_k - mu_k) / std_k

            S[:, k] = s_k
        return S

    def predict_proba(self, X):
        check_is_fitted(self, ["pineforests_", "classes_"])
        X = check_array(X, accept_sparse=False, dtype=np.float64)

        if self.calibration == "discriminator":
            S = self._get_raw_scores(X, apply_zscore=True)
            return self.discriminator_.predict_proba(S)

        S = self._get_raw_scores(X)
        L = self.global_scale * S + self.log_class_priors_

        max_L = np.max(L, axis=1, keepdims=True)
        exp_L = np.exp(L - max_L)
        Z = exp_L.sum(axis=1, keepdims=True)
        return exp_L / Z

    def predict(self, X):
        P = self.predict_proba(X)
        idx = np.argmax(P, axis=1)
        return self.classes_[idx]


class AADForestGenerativeClassifier(ClassifierMixin, BaseEstimator):
    """Multiclass classifier built from one-vs-rest AADForest models.

    One AADForest is fit per class using coniferest AAD labels, marking the
    target class as regular and all remaining classes as anomalous. The
    resulting classwise scores are calibrated and converted into multiclass
    probabilities using quantile, z-score, or discriminator calibration.
    """

    _estimator_type = "classifier"
    _eps = 1e-12

    def __init__(
        self,
        n_estimators=100,
        max_samples=256,
        bootstrap=False,
        n_jobs=None,
        random_state=None,
        verbose=0,
        max_depth=None,
        calibration="discriminator",
        global_scale=1.0,
    ):
        self.n_estimators = n_estimators
        self.max_samples = max_samples
        self.bootstrap = bootstrap
        self.n_jobs = n_jobs
        self.random_state = random_state
        self.verbose = verbose
        self.max_depth = max_depth
        self.calibration = calibration
        self.global_scale = global_scale

    def _make_aadforest(self, random_state):
        return AADForest(
            n_trees=self.n_estimators,
            n_subsamples=self.max_samples,
            max_depth=self.max_depth,
            # AADForest does not expose bootstrap or verbose parameters.
            n_jobs=-1 if self.n_jobs is None else self.n_jobs,
            random_seed=random_state,
        )

    def _score_aad_class_normality(self, model, X):
        # AADForest scores are anomaly scores: lower values are more anomalous,
        # so larger values already mean the sample better matches the positive class.
        return model.score_samples(X)

    def fit(self, X, y):
        X, y = check_X_y(X, y, accept_sparse=False, dtype=np.float64)

        self.le_ = LabelEncoder()
        y_enc = self.le_.fit_transform(y)
        self.classes_ = self.le_.classes_
        n_classes = len(self.classes_)

        if n_classes < 2:
            raise ValueError("Need at least 2 classes.")

        self.n_classes_ = n_classes
        self.class_priors_ = np.bincount(y_enc) / float(len(y))
        self.log_class_priors_ = np.log(self.class_priors_ + self._eps)

        self.aadforests_ = []
        self.calibrators_ = []

        rng = np.random.RandomState(self.random_state)

        for k in range(n_classes):
            rs_k = None if self.random_state is None else rng.randint(0, 2**31 - 1)
            aadforest_k = self._make_aadforest(random_state=rs_k)

            labels_k = np.where(y_enc == k, Label.REGULAR, Label.ANOMALY)
            aadforest_k.fit(X, labels=labels_k)
            self.aadforests_.append(aadforest_k)

            # Calibrate on the full training set because each AAD model is trained
            # against the full one-vs-rest label distribution over X.
            scores_k = self._score_aad_class_normality(aadforest_k, X)

            if self.calibration == "quantile":
                qt = QuantileTransformer(output_distribution="normal", n_quantiles=min(len(X), 1000))
                qt.fit(scores_k.reshape(-1, 1))
                self.calibrators_.append(qt)
            elif self.calibration == "zscore" or self.calibration == "discriminator":
                mu_k = scores_k.mean()
                std_k = scores_k.std()
                if std_k <= 0:
                    std_k = 1.0
                self.calibrators_.append((mu_k, std_k))
            else:
                raise ValueError("calibration must be one of {'quantile', 'zscore', 'discriminator'}")

        if self.calibration == "discriminator":
            S_train = self._get_raw_scores(X, apply_zscore=True)
            self.discriminator_ = LogisticRegression(class_weight="balanced")
            self.discriminator_.fit(S_train, y_enc)

        self.n_features_in_ = X.shape[1]
        return self

    def _get_raw_scores(self, X, apply_zscore=False):
        n_samples = X.shape[0]
        S = np.zeros((n_samples, self.n_classes_), dtype=float)

        for k, aadforest_k in enumerate(self.aadforests_):
            s_k = self._score_aad_class_normality(aadforest_k, X)

            if self.calibration == "quantile":
                s_k = self.calibrators_[k].transform(s_k.reshape(-1, 1)).flatten()
            elif apply_zscore or self.calibration == "zscore":
                mu_k, std_k = self.calibrators_[k]
                s_k = (s_k - mu_k) / std_k

            S[:, k] = s_k
        return S

    def predict_proba(self, X):
        check_is_fitted(self, ["aadforests_", "classes_"])
        X = check_array(X, accept_sparse=False, dtype=np.float64)

        if self.calibration == "discriminator":
            S = self._get_raw_scores(X, apply_zscore=True)
            return self.discriminator_.predict_proba(S)

        S = self._get_raw_scores(X)
        L = self.global_scale * S + self.log_class_priors_

        max_L = np.max(L, axis=1, keepdims=True)
        exp_L = np.exp(L - max_L)
        Z = exp_L.sum(axis=1, keepdims=True)
        return exp_L / Z

    def predict(self, X):
        P = self.predict_proba(X)
        idx = np.argmax(P, axis=1)
        return self.classes_[idx]


if __name__ == "__main__":
    from sklearn.datasets import make_classification

    X, y = make_classification(
        n_samples=90,
        n_features=6,
        n_informative=5,
        n_redundant=0,
        n_classes=3,
        n_clusters_per_class=1,
        random_state=0,
    )
    clf = PineForestGenerativeClassifier(
        n_estimators=25,
        max_samples=32,
        calibration="zscore",
        random_state=0,
    )
    clf.fit(X, y)
    print(clf.predict_proba(X[:5]))
    print(clf.predict(X[:5]))
